# Try-catch
trying my first exception 
try {
     method();
     } catch (someException) {
     system.out.println("Never mind lets keep going");
     }
